name: Release workflow

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  maven-build:
    name: Maven build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
          server-id: github
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
        with:
          git-release-bot-name: "bot-idhub"
          git-release-bot-email: "bot@idhub.io"

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"
          version-patch: true
          skip-perform: true
          release-branch-name: "main"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - run: mvn -B -Dmaven.test.skip=true -DuseReleaseProfile=false -DpreparationGoals=clean release:clean release:prepare -DtagNameFormat=demo-@{project.version}
      # - run: mvn -B release:perform -Darguments="-Dmaven.javadoc.skip=true -DskipTests"
