name: Release workflow

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  maven-build:
    name: Maven build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
          server-id: github
      - run: npm version patch -no-git-tag-version
      - run: echo "APP_VERSION=$(npm pkg get version)" >> $GITHUB_ENV
      - run: mvn -B versions:set -DnewVersion=${{ env.APP_VERSION }} versions:commit 
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] version bump"
          tagging_message: "${{ env.APP_VERSION }}"
      # - run: npm version patch
      # - name: Release
      #   uses: qcastel/github-actions-maven-release@master
      #   env:
      #     JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
      #   with:
      #     git-release-bot-name: "bot-idhub"
      #     git-release-bot-email: "bot@idhub.io"

      #     maven-args: "-Dmaven.javadoc.skip=true -Dmaven.test.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true -DpreparationGoals=clean release:clean release:prepare"
      #     version-patch: true
      #     skip-perform: true
      #     release-branch-name: "main"
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - run: mvn -B -Dmaven.test.skip=true -DuseReleaseProfile=false -DpreparationGoals=clean release:clean release:prepare -DtagNameFormat=demo-@{project.version}
      # - run: mvn -B release:perform -Darguments="-Dmaven.javadoc.skip=true -DskipTests"
