name: VERSION workflow

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  maven-build:
    name: Maven build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
          server-id: github
      - if: ${{ contains(github.ref, '/feature/') || contains(github.ref, '/feat/')  }}
        run: yarn version --minor --no-git-tag-version
      - if: ${{ contains(github.ref, '/bug/') || contains(github.ref, '/bugfix/') || contains(github.ref, '/hotfix/') || contains(github.ref, '/chore/')  }}
        run: yarn version --patch --no-git-tag-version
      - run: echo "APP_VERSION=$(sed -e 's/^"//' -e 's/"$//' <<<$(npm pkg get version))" >> $GITHUB_ENV
      - run: mvn --batch-mode --no-transfer-progress versions:set -DnewVersion=${{ env.APP_VERSION }} versions:commit

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] version bump: ${{ env.APP_VERSION }}"