name: VERSION workflow

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  maven-build:
    name: Maven build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven
          server-id: github
      - run: echo "BUILD_NUMBER=$(npm pkg get version | sed -e 's/^"//' -e 's/"$//' | cut -d '.' -f3)" >> $GITHUB_ENV
      - run: echo "HEAD=$(npm pkg get version | sed -e 's/^"//' -e 's/"$//' | cut -d '.' -f1)" >> $GITHUB_ENV
      - run: echo "YEAR=$(cut -c3-4 <<< $(date +%Y))" >> $GITHUB_ENV
      - run: echo "WEEK=$(date +%V)" >> $GITHUB_ENV
      - run: echo "APP_VERSION=${{env.HEAD}}${{env.YEAR}}${{env.WEEK}}${{env.BUILD_NUMBER}}" >> $GITHUB_ENV
      - run: echo ${{env.APP_VERSION}}
#      - run: mvn -B versions:set -DnewVersion=${{ env.APP_VERSION }} versions:commit
#
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "[ci skip] release version: ${{ env.APP_VERSION }}"
#          tagging_message: ${{ env.APP_VERSION }}